# Generated by Django 4.2.3 on 2023-08-17 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.PositiveIntegerField(default=18)),
                ('email', models.EmailField(max_length=254, verbose_name='')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('fitness_goal', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('description', models.TextField(blank=True, null=True)),
                ('public', models.BooleanField(default=False, verbose_name='Publicly Accessible')),
                ('completed', models.BooleanField(default=False)),
                ('exercises', models.ManyToManyField(to='WorkoutApp.exercise')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkoutApp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkoutApp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('repetitions', models.IntegerField(default=0)),
                ('sets', models.IntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kilograms or pounds.', max_digits=5, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkoutApp.exercise')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkoutApp.profile')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkoutApp.workout')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkoutApp.exercisetype'),
        ),
    ]
