# Generated by Django 4.2.3 on 2023-08-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutApp', '0002_alter_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisetype',
            name='name',
            field=models.CharField(choices=[('Upper Body', 'Upper Body'), ('Core', 'Core'), ('Lower Body', 'Lower Body'), ('Full Body', 'Full Body')], max_length=100, unique=True),
        ),
    ]
