# Generated by Django 4.2.3 on 2023-08-18 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutApp', '0002_workoutprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='public',
        ),
        migrations.CreateModel(
            name='NutritionTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('food_item', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='E.g., grams, ounces, cups, etc.', max_digits=5)),
                ('calories', models.IntegerField(help_text='Calories contained in the food item.')),
                ('notes', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkoutApp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='DailyTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('activity', models.CharField(help_text='E.g., walking, running, yoga, etc.', max_length=200)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('notes', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkoutApp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('date_achieved', models.DateField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkoutApp.profile')),
            ],
        ),
    ]
