# Generated by Django 4.2.3 on 2023-08-07 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutApp', '0004_alter_exercise_type_alter_exercisetype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkoutApp.profile'),
        ),
    ]
