# Generated by Django 4.2.3 on 2023-08-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutApp', '0006_alter_workout_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
