# Generated by Django 4.2.3 on 2023-08-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutApp', '0007_workout_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Publicly Accessible'),
        ),
    ]
