# Generated by Django 4.2.3 on 2023-08-12 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutApp', '0008_workout_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='repetitions',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='sets',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='fake@email.com', max_length=254, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkoutApp.exercisetype'),
        ),
        migrations.CreateModel(
            name='ProfileHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkoutApp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('repetitions', models.IntegerField()),
                ('sets', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kilograms or pounds.', max_digits=5, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkoutApp.exercise')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkoutApp.profile')),
            ],
        ),
        migrations.AlterField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(to='WorkoutApp.exerciseprogress'),
        ),
    ]
